root: true
env:
  es6: true
  browser: true
parserOptions:
  ecmaVersion: 2017
extends:
  - airbnb
  - plugin:flowtype/recommended
  - prettier
  - prettier/react
  - prettier/flowtype
plugins:
  - flowtype
  - prettier
rules:
  react/require-default-props: 0
  react/sort-comp: 0
  import/extensions: 0
  import/no-unresolved: 0
