root: true
env:
  es6: true
  browser: true
parserOptions:
  ecmaVersion: 2017
extends:
  - airbnb
  - plugin:flowtype/recommended
  - prettier
  - prettier/react
  - prettier/flowtype
  - plugin:jest/recommended
plugins:
  - flowtype
  - prettier
  - jest
rules:
  react/jsx-filename-extension: 0
  react/prefer-stateless-function: 0
  react/require-default-props: 0
  react/sort-comp: 0
  import/extensions: 0
  import/no-unresolved: 0
  no-underscore-dangle: 0
